from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Annotated, Literal, Union

from pydantic import BaseModel, Field, field_validator, model_validator

from domain.actions import Action


class PetStats(BaseModel):
    hunger: float = Field(..., ge=0.0, le=1.0)
    boredom: float = Field(..., ge=0.0, le=1.0)
    social: float = Field(..., ge=0.0, le=1.0)
    toilet: float = Field(..., ge=0.0, le=1.0)
    tiredness: float = Field(..., ge=0.0, le=1.0)


class SceneObject(BaseModel):
    id: str
    type: Literal["bowl", "bed", "toy", "player", "pet"]
    distance: float


class SceneData(BaseModel):
    objects: list[SceneObject]
    tick: int


class InferenceRequest(BaseModel):
    scene: SceneData
    pet_stats: PetStats


class InferenceResponse(BaseModel):
    stat: str | None = None
    action: Action
    target_object_id: str | None = None
    confidence: float | None = None


class EvalOutcome(str, Enum):
    """Outcome of a discrete eval run (separate from run completion status)."""
    SUCCEEDED = "succeeded"
    FAILED = "failed"


class TrainJobSpec(BaseModel):
    """Job spec for a remote training job (replaces RemoteTrainConfig)."""
    job_type: Literal["train"] = "train"
    model: str
    train_data: str
    eval_data: str
    epochs: int
    patience: int
    warmup_ratio: float
    experiment_name: str
    gpu_type: str = "NvidiaTeslaT4"
    # DB run-record UUID used as the S3 key prefix (workflow/{run_id}/) so all
    # backends write to the same path.  Adapters fall back to a random UUID when empty.
    run_id: str = ""


# Backward-compat alias so existing code using RemoteTrainConfig continues to work.
RemoteTrainConfig = TrainJobSpec


class EvalJobSpec(BaseModel):
    """Job spec for a remote eval job dispatched via RemoteJobPort."""
    job_type: Literal["eval"] = "eval"
    experiment_name: str
    # Adapter-agnostic reference to the training artifact:
    # - RunPod/VastAI: S3 run_id prefix (e.g. "workflow/abc123")
    # - Kaggle: training kernel slug (e.g. "username/exp-slug")
    training_artifact_ref: str
    eval_data: str   # S3 key or local path to eval.jsonl
    gpu_type: str = "NvidiaTeslaT4"
    # S3 key prefix for this eval job; generated by workflow at start.
    run_id: str = ""


class ExportJobSpec(BaseModel):
    """Job spec for a remote GGUF-export job dispatched via RemoteJobPort.

    The K8s export Job downloads the checkpoint from S3, converts it to a
    quantised GGUF using llama.cpp (pre-built in the export image), and
    uploads the result back to S3.  The Temporal worker does NOT need
    llama.cpp installed — it only submits this spec and polls status().
    """
    job_type: Literal["export"] = "export"
    # DB run_id — used as the S3 key namespace: workflow/{experiment_name}/…
    experiment_name: str
    # S3 prefix for the HuggingFace checkpoint produced by the training job.
    # Must end with "/".  Example: "workflow/{run_id}/checkpoint/"
    checkpoint_s3_prefix: str
    # S3 key the finished GGUF will be written to.
    # Example: "workflow/{run_id}/model.gguf" or "gguf/{model_name}.gguf"
    gguf_s3_key: str
    # llama.cpp quantisation format (default matches the inference image target).
    quantize: str = "Q4_K_M"


# Discriminated union — adapters accept a train, eval, or export job.
RemoteJobSpec = Annotated[
    Union[TrainJobSpec, EvalJobSpec, ExportJobSpec],
    Field(discriminator="job_type"),
]


class TrainingModelConfig(BaseModel):
    name: str
    description: str = ""
    base_model: str = "HuggingFaceTB/SmolLM2-360M"
    train_data: str = "data/train.jsonl"
    eval_data: str = "data/eval.jsonl"
    epochs: int = 5
    patience: int = 3
    warmup_ratio: float = 0.05
    remote_backend: str = "local"
    skip_generate: bool = False
    gguf_path: str = ""
    is_active: bool = False
    owner_id: str | None = None
    backend: Literal["local", "openrouter"] = "local"
    backend_model_id: str = ""

    @model_validator(mode="after")
    def check_openrouter_model_id(self) -> "TrainingModelConfig":
        if self.backend == "openrouter" and not self.backend_model_id:
            raise ValueError("backend_model_id is required when backend='openrouter'")
        return self


class TrainingModel(TrainingModelConfig):
    id: str
    created_at: datetime
    updated_at: datetime


class RunStatus(str, Enum):
    PENDING = "pending"
    GENERATING = "generating"
    TRAINING = "training"
    EVALUATING = "evaluating"
    EXPORTING = "exporting"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"
    CANCELLED = "cancelled"


class RunConfig(BaseModel):
    model_id: str
    workflow_id: str
    training_config: dict | None = None  # full training params saved at trigger time
    train_dataset_id: str | None = None
    eval_dataset_id: str | None = None
    owner_id: str | None = None


class RunRecord(RunConfig):
    id: str
    status: RunStatus
    eval_valid_pct: float | None = None
    eval_result: EvalOutcome | None = None  # None until eval runs
    progress: float | None = None
    progress_detail: str | None = None
    created_at: datetime
    updated_at: datetime


class UserContext(BaseModel):
    user_id: str
    email: str | None = None
    roles: list[str] = []
    status: Literal["pending", "approved"] | None = None


class StatAccuracyResult(BaseModel):
    correct: int
    total: int
    accuracy: float = Field(ge=0.0, le=1.0)
    passed: bool


class CategoryAccuracyResult(BaseModel):
    correct: int
    total: int
    accuracy: float = Field(ge=0.0, le=1.0)
    passed: bool


_REQUIRED_STATS = frozenset(["hunger", "boredom", "social", "tiredness", "toilet"])


class QualityReport(BaseModel):
    per_stat_accuracy: dict[str, StatAccuracyResult]
    target_accuracy: CategoryAccuracyResult
    priority_conflict: CategoryAccuracyResult
    fallback_accuracy: CategoryAccuracyResult
    action_distribution: dict[str, int]
    max_action_share: float
    passed: bool

    @field_validator("per_stat_accuracy")
    @classmethod
    def _all_stats_present(cls, v: dict) -> dict:
        missing = _REQUIRED_STATS - v.keys()
        if missing:
            raise ValueError(f"Missing stats in per_stat_accuracy: {missing}")
        return v


class EvaluationData(BaseModel):
    run_id: str
    status: RunStatus
    eval_valid_pct: float | None = None
    quality_report: QualityReport | None = None


class DatasetType(str, Enum):
    TRAIN = "train"
    EVAL = "eval"


class DatasetConfig(BaseModel):
    name: str
    description: str = ""
    dataset_type: DatasetType
    key: str  # storage key, e.g. "datasets/{id}.jsonl"
    owner_id: str | None = None


class DatasetRecord(DatasetConfig):
    id: str
    created_at: datetime
    updated_at: datetime


class InferenceStatus(str, Enum):
    PENDING = "pending"
    INITIALIZING = "initializing"
    AVAILABLE = "available"
    IDLE = "idle"
    SHUTDOWN = "shutdown"
    FAILED = "failed"


class InferenceInstanceConfig(BaseModel):
    model_id: str
    pod_name: str = ""
    pod_namespace: str = "default"
    idle_timeout_minutes: int = 120


class InferenceInstance(InferenceInstanceConfig):
    id: str
    status: InferenceStatus = InferenceStatus.PENDING
    last_used_at: datetime | None = None
    created_at: datetime
    updated_at: datetime
